services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yml
      - --api.insecure=true
    ports:
      - "8081:8080"
      - "8082:80" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
